### ISSUE TITLE
Time to ship

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#151]
Let's ship a beta! What do we still have to do before then?

- [x] Finish cast controls (#148)
- [x] Open .torrent files and magnet links (#77)
- [x] Prevent multiple copies of WebTorrent from running simultaneously (#167)
- [x] Nicer error messages. No more alert()s, show a red bar or popover
- [x] Save torrent data in state.saved (#169)
- [x] Make sure already downloaded files can play even when we're offline
- [x] Website

What else?

**Comment by iadj** [comment]
'Run in background mode' for consistent seeding/downloading while the OS is running: https://github.com/feross/webtorrent-app/issues/150

**Comment by ChrisMorrisOrg** [comment]
I feel like we're getting close to a beta release too. I'll be working on the preferences window tomorrow, plan to finish before the weekend is over.

**Comment by feross** [comment]
@dcposch Your list looks good to me.

**Comment by feross** [comment]
We need to set WebTorrent to open .torrent files and magnet links on all OSs. #77 Will add to the launch checklist.

**Comment by ungoldman** [comment]
We should test with network connection off. In the last build I tried torrents that were fully downloaded would never load into the app, probably because the webtorrent client is waiting to get metadata from the infohash first.

**Comment by feross** [comment]
@ungoldman Yep. That should be fixed by saving the `torrent.torrentFile` in state.saved instead of just the `torrent.infoHash`.

Prefs dialog would be great to have, but it's not a launch blocker – removed it from the list.

And, now that the Windows app supports opening magnet links, #167 has become very important. Added it to the list.

**Comment by feross** [comment]
Woot – looks like all that's left is a website? Can that really be it?!!

**Comment by dcposch** [comment]
https://github.com/feross/webtorrent-www/pull/47

**Comment by ungoldman** [comment]
aw damn really? I literally just finished http://ungoldman.github.io/webtorrent-app-www/. lol.

**Comment by ungoldman** [comment]
Source is here if it's at all useful. https://github.com/ungoldman/webtorrent-app-www/

**Comment by iadj** [comment]
@ungoldman I really like this one. Perhaps we can combine this version with the download buttons on @dcposch's version? That way there's installation options for both basic & advanced users.

**Comment by ungoldman** [comment]
I'll try integrating some of what I did into @dcposch's work on `webtorrent-www`.

**Comment by ungoldman** [comment]
So https://github.com/ungoldman/webtorrent-app-www/ is literally just converting all the markdown files in this repo into html pages using `webtorrent-www`'s style as a layout. I think @dcposch's page is a better way to present the information on the site though we may want to explore including more info or documentation on the site later.

I've opened a PR (feross/webtorrent-www#48) building on @dcposch's work from yesterday.

**Comment by feross** [comment]
@ungoldman Nice, I like your changes.

**Comment by dcposch** [comment]
Sweet: https://webtorrent.io/desktop
