### ISSUE TITLE
WebTorrent 1.0 checklist

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#652]
@feross from our conversation yesterday:

- [ ] Cast menu
- [ ] Growth tracking: # of active users, month over month growth
- [ ] UI polish. Improve the CSS
- [ ] Technical debt cleanup
  - [ ] Split up `renderer/main.js`
  - [ ] Eliminate uncaught exceptions as best we can
- [ ] Telemetry
  - [ ] Report uncaught exceptions
  - [ ] Maybe report % of times the play button Just Works, % times out, % shows unsupported codec error
- [ ] Performance
  - [ ] Profile and see what's making WebTorrent sluggish
  - [ ] Reduce CPU use
- [ ] Better codec support
  - [ ] "Play in VLC" should allow casting instead; the cast devices have AC3 support
  - [ ] Ideally, we should just support AC3. On Windows and Mac, we could use the system codec support

**Comment by feross** [comment]
:+1:

**Comment by dcposch** [comment]
Also:
- [ ] Bounds refactor. Save the latest *non-player* window bounds, and restore to those whenever existing the player. This should fix #648 as well as a bug I just discovered: play video > start casting > stop casting > hit ESC returns to the torrent list as expected, but does not restore the original window bounds.

**Comment by dcposch** [comment]
- [ ] Autoplay files within a torrent. Until we can do this we don't really support audiobooks.

**Comment by dcposch** [comment]
- [ ] Cast refactor. Simplify state (state.playing / state.devices etc)
  - [ ] When casting to a device fails, the corresponding cast menu item shouldn't be checked
  - [ ] New cast devices should show up without rebooting the app. Same for removing cast devices. Currently this doesn't work reliably for DLNA.
  - [ ] When you're eg. streaming to Chromecast from WTD, then you unplug the Chromecast, it should kick you back to the regular player and remove the corresponding cast menu item

**Comment by feross** [comment]
Just shipped WebTorrent v0.11. https://github.com/feross/webtorrent-desktop/releases/tag/v0.11.0

Hoping we can do one more release (v0.12) in the next few days, and then hopefully we're ready for v1.0!

**Comment by bertofer** [comment]
Hi guys,

Regarding:
- [ ] Clarify download status (see #715), we could use a 'pause' or 'stop' button. I read over the issue and saw @dcposch comment about the pause button being confusing next to a Play button, but wanted to try it anyway. For me is more clarifying than the current status. Also, it helps the fact that the red play button never becomes a pause button (as it only opens the player). I leave some screenshots:

<img width="494" alt="screen shot 2016-08-29 at 18 51 45" src="https://cloud.githubusercontent.com/assets/1634229/18061275/113e5216-6e1a-11e6-80df-43c9b951bcc4.png">

<img width="494" alt="screen shot 2016-08-29 at 18 52 13" src="https://cloud.githubusercontent.com/assets/1634229/18061279/1336de44-6e1a-11e6-9422-5e898b9cdecb.png">

When torrent is already paused, it will show the current download/upload icons.

For 
- [ ] Clarify that torrents can be expanded / collapsed, I am trying with some arrows before the current buttons, I leave some screenshots:

<img width="496" alt="screen shot 2016-08-29 at 19 07 31" src="https://cloud.githubusercontent.com/assets/1634229/18061794/00edc098-6e1c-11e6-981d-3f42925e0857.png">

<img width="494" alt="screen shot 2016-08-29 at 19 07 49" src="https://cloud.githubusercontent.com/assets/1634229/18061799/05ed766a-6e1c-11e6-8088-440b0b6a282c.png">

What do you think? kind to open PR on this

**Comment by iovis9** [comment]
I still think it's confusing having a big play button with the pause/stop one. Maybe a solution would be having them in different places instead of next to each other?

**Comment by bertofer** [comment]
@iovis9 Agree, maybe having the torrenting button more aligned with the torrent metadata and leave the 'play' button alone would be more clarifying. This would need a bit more of design, though.

As for now, I have tried with the pause/reload button just **on hover**, so the torrenting status is still visible at first sight. You can have a look here https://github.com/bertofer/webtorrent-desktop

**Comment by iovis9** [comment]
I was thinking something more on the lines of this (2-minute hack, just an idea).

![screen shot 2016-08-31 at 21 29 21](https://cloud.githubusercontent.com/assets/6660202/18143372/05e70422-6fc2-11e6-8059-a721213f8e2e.png)

**Comment by bertofer** [comment]
Don't post those torrents 🙉 !

I like the idea, yes. I think it can be combined with having pause icon only on hover, so you still see if torrent is downloading/seeding, and as a meaning of what the button is about.

**Comment by dcposch** [comment]
@iovis9 We don't support the use of WebTorrent for copyright infringement, and cannot help you.

**Comment by dcposch** [comment]
@bertofer Thanks for the ideas. Let's move the torrent list designs to their own issue.

**Comment by feross** [comment]
I think we're really close to 1.0. I just updated the checkboxes. Better codec support is the most important remaining issue, IMO.

**Comment by iShift** [comment]
and heavy CPU usage too, when i lunch webtorrent on MBP i start hearing fans inside (qbittorrent work quiet)
